### ISSUE TITLE
Add Scala 3 crossbuild

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-collection-contrib#119]
volunteer?

it probably works with `withDottyCompat`, but it's better to have a "real" Scala 3 artifact

**Comment by SethTisue** [comment]
Scala 3.0.0 is out. Volunteer?

**Comment by povder** [comment]
My attempt: https://github.com/scala/scala-collection-contrib/pull/166

**Comment by Philippus** [comment]
Fixed in https://github.com/scala/scala-collection-contrib/pull/166.
