### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by j-mie6** [scala/scala-collection-contrib#189]
Would it be possible to get a new release pushed out for the Scala Native support? Thanks.

**Comment by SethTisue** [comment]
(note to self: badge in readme will need update, since we've added Scala 3 support. the readme should probably mention Scala.js and Scala Native availability too)

**Comment by SethTisue** [comment]
* release: https://github.com/scala/scala-collection-contrib/releases/tag/v0.3.0
* publishing job: https://github.com/scala/scala-collection-contrib/actions/runs/3372250795
* artifacts: https://repo1.maven.org/maven2/org/scala-lang/modules/

**Comment by SethTisue** [comment]
readme updates: 60251e16830c06ec6dcd7913af0163cc8337e7f7 (I removed the badge)
