### ISSUE TITLE
Release for Scala 2.13.0

### ISSUE THREAD

**Issue by Toromtomtom** [scala/scala-collection-contrib#20]
All tests pass when using Scala 2.13.0. Does this mean that this project is ready for to be released?

**Comment by SethTisue** [comment]
related: #3

**Comment by Toromtomtom** [comment]
I opened a pull request to get this going: https://github.com/scala/scala-collection-contrib/pull/22

**Comment by SethTisue** [comment]
thanks @Toromtomtom for moving this forward! as @julienrf said on your PR,

> in order to effectively publish releases we also need to provide secrets (sonatype credentials) to the Travis CI

I can tackle this, but the earliest I could get to it is next week.

**Comment by SethTisue** [comment]
at the time we publish, we should also figure out where to publicize it, as per https://github.com/scala/docs.scala-lang/issues/1097

**Comment by SethTisue** [comment]
* tag https://github.com/scala/scala-collection-contrib/releases/tag/v0.1.0
* publish  job https://travis-ci.org/scala/scala-collection-contrib/jobs/560717547

**Comment by SethTisue** [comment]
when I try to close the staging repo,`No public key: Key with id: (951c6f43ce4b08c9) was not able to be located on <a href="http://pool.sks-keyservers.net:11371/">http://pool.sks-keyservers.net:11371/</a>. Upload your public key and try the operation again.`

perhaps something needs time to propagate from https://pgp.mit.edu to... somewhere. I'll try it again later

**Comment by SethTisue** [comment]
I also submitted the key to a number of the other servers that the Sonatype log showed it was trying, and eventually closing the repository worked, not sure whether it was time passing that did or it, or the additional submissions.

so, closed & released. now we wait for artifacts to appear here: https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-contrib_2.13/

**Comment by SethTisue** [comment]
```
[info] Updating 
http://127.0.0.1:8081/artifactory/scala-ci-virtual/org/scala-lang/modules/scala-collection-contrib_2.13/0.1.0/scala-collection-contrib_2.…
  100.0% [##########] 2.4 KiB (6.0 KiB / s)
[info] Resolved  dependencies
[info] Fetching artifacts of 
[info] Fetched artifacts of 
[info] Starting scala interpreter...
Welcome to Scala 2.13.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_202).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.decorators._
import scala.collection.decorators._

scala> Seq(1,2,3).intersperse(5)
res0: Seq[Int] = List(1, 5, 2, 5, 3)
```

:+1:

**Comment by SethTisue** [comment]
> at the time we publish, we should also figure out where to publicize it

made a separate ticket on this: #32
