### ISSUE TITLE
After first release/publish, set up MiMa to enforce bincompat

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-collection-contrib#23]
backwards-only is fine, and I think we could give ourselves permission to be liberal about bumping the version number as needed, in order not to be too saddled by this

**Comment by SethTisue** [comment]
waiting on #20 for now

**Comment by SethTisue** [comment]
fixed in #33

**Comment by joshlemer** [comment]
Could we wait to ping Mima / backwards compatibility until after https://github.com/scala/scala-collection-contrib/pull/24 ?

**Comment by SethTisue** [comment]
I'm fine with considering the MiMa results just informational for now.
