### ISSUE TITLE
Support Scala Native 0.5

### ISSUE THREAD

**Issue by j-mie6** [scala/scala-collection-contrib#251]
Currently, this library only supports Scala native 0.4: it would be good if a release was make to 0.5, either as a switch over, or cross-published to both (as I believe scalatest does).

**Comment by SethTisue** [comment]
The upgrade has been merged, so we just need to publish. I can take care of it.

I'll need to get sbt-ci-release going here, after which future releases will be easier to do.

**Comment by SethTisue** [comment]
oh, sbt-ci-release is already here. I must have looked at `project/plugins.sbt` and forgot that `sbt-scala-module` includes `sbt-co-release`

**Comment by SethTisue** [comment]
https://github.com/scala/scala-collection-contrib/releases/tag/v0.4.0

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-contrib_3/0.4.0

**Comment by SethTisue** [comment]
hmm, compile errors at https://github.com/scala/scala-collection-contrib/actions/runs/11420889032/job/31777091558

**Comment by SethTisue** [comment]
okay https://github.com/scala/scala-collection-contrib/pull/259 should do the trick

**Comment by SethTisue** [comment]
https://github.com/scala/scala-collection-contrib/actions/runs/11421104284

**Comment by SethTisue** [comment]
looks like I need to regenerate the GPG key

**Comment by SethTisue** [comment]
https://github.com/scala/scala-collection-contrib/actions/runs/11421104284
https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-contrib_3/0.4.0
