### ISSUE TITLE
publish 0.2.0

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-collection-contrib#47]
it's tagged but not published, the staging repos wouldn't close. I'll come back to it

**Comment by SethTisue** [comment]
when I checked back, the staging repos had finally closed. so I hit "Release"

now we watch https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-contrib_2.13/0.2.0/

**Comment by julienrf** [comment]
Thanks for managing that!

**Comment by SethTisue** [comment]
would someone like to tweet about the release? I can retweet from scala_lang
