### ISSUE TITLE
Broken 0.2.0 artifact (no .class files in .jar)

### ISSUE THREAD

**Issue by linasm** [scala/scala-collection-contrib#51]
`scala-collection-contrib_2.13-0.2.0.jar` is missing .class files (it only has .properties file and manifest)

https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-contrib_2.13/0.2.0/scala-collection-contrib_2.13-0.2.0.jar

@SethTisue @julienrf

**Comment by harpocrates** [comment]
Just hit this too...

**Comment by mpollmeier** [comment]
While we're waiting for a usable artifact I published a jar to my bintray - anyone else wants to use it:
```
libraryDependencies += "com.michaelpollmeier" %% "scala-collection-contrib" % "0.2.1"
resolvers += Resolver.bintrayRepo("mpollmeier", "maven")
```
https://github.com/mpollmeier/scala-collection-contrib/releases/tag/v0.2.1
(I simply ripped out scalajs from the build).

**Comment by skradel** [comment]
Ditto, the (essentially empty) artifact gave rise to a certain amount of head-scratching; using 0.1.0 for the time being to quiet MultiMap deprecation warnings.

**Comment by SethTisue** [comment]
this is an OSGi / sbt-osgi problem. it's similar to https://github.com/scala/community-build/issues/981 and https://github.com/scala/scala-parallel-collections/issues/5

**Comment by SethTisue** [comment]
one thing we might consider here is whether this stuff ought to be under `scala.collection` (or any other `scala.` subpackage) at all

**Comment by SethTisue** [comment]
another possibility is to just disable the OSGi stuff in this repo, and document it as a limitation that we'd welcome community help with but don't plan to tackle ourselves (the core Scala team). Adriaan has already said he's fine with that (and there wasn't any dissent within the team)

I'll poke at sbt-osgi and sbt-scala-module and see what I think that would involve

**Comment by SethTisue** [comment]
> another possibility is to just disable the OSGi stuff in this repo

yeah, let's do that, it turned out to be relatively easy

PR with fix: #72 
issue to document lack of OSGi support: #71 

unless there are objections, I'll merge the PR and publish after Christmas

**Comment by SethTisue** [comment]
PR merged. next: publishing

**Comment by SethTisue** [comment]
* tag, release notes: https://github.com/scala/scala-collection-contrib/releases/tag/v0.2.1
* release build: https://travis-ci.org/scala/scala-collection-contrib/builds/630999627
* 3 staging repos released via Sonatype web UI
* post-release README updates: 3c0929910d1312a2bbadd9bec4e9e3d00dfd7596
* artifacts on Maven Central soon: https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-contrib_2.13/0.2.1/
