### ISSUE TITLE
Can Scala 2.12 be supported?

### ISSUE THREAD

**Issue by ngocdaothanh** [scala/scala-collection-contrib#66]
https://www.scala-lang.org/api/current/scala/collection/mutable/MultiMap.html
says:
"(Since version 2.13.0) Use a scala.collection.mutable.MultiDict in the scala-collection-contrib module"

I'd like to use `MultiDict` in a project that I want to support both Scala 2.12 and 2.13.

Can scala-collection-contrib also support Scala 2.12?

**Comment by SethTisue** [comment]
Sorry, it's out of scope for us, the 2.12 and 2.13 collections designs are too different.

But, you could publish that as a separate library yourself, if you want to tackle a 2.12 backport.
