### ISSUE TITLE
Change values returned from SortedMultiDict to be a SortedSet[V]

### ISSUE THREAD

**Issue by er1c** [scala/scala-collection-contrib#97]
Considering the distinction of a `SortedMultiDict` vs a `MultiDict` is the sorting, it seems reasonable to me that the returned values should also retain the relative ordering as they were added to the collection.

Scaladoc: https://www.javadoc.io/doc/org.scala-lang.modules/scala-collection-contrib_2.13/latest/scala/collection/SortedMultiDict.html

As a reference, this is how the type signature is in Guava: https://guava.dev/releases/19.0/api/docs/index.html?com/google/common/collect/ListMultimap.html

**Comment by joshlemer** [comment]
I don't think this necessarily follows. The 'Sorted' in 'SortedMultiMap' refers to the fact that the keys are sorted, but it's not true that the values are also sorted. The Guava interface linked to is also not sorting the values, it's only keeping the values in insertion order.

**Comment by joshlemer** [comment]
Closing because SortedMultiDict values are not sorted (nor unique) and so can't be viewed as a SortedSet, thanks!
