### ISSUE TITLE
Rename MultiDict back to original MultiMap or SetMultiMap

### ISSUE THREAD

**Issue by er1c** [scala/scala-collection-contrib#98]
I think it may make the most sense to rename `MultiDict` to `SetMultiMap`, and potentially make `MultiMap` into a generic trait.

1) It helps remove the @deprecation warning if renamed back to `MultiMap`
2) "MultiMap" is a more universally used terminology for this type of collection.  (e.g. Guava has `ArrayListMultimap`, `ListMultimap`, `SetMultimap`, and etc; C++ STL is `std::multimap`; Rust is `MultiMap`, Apache Commons is `MultiMap`, etc) 
3) The existing name also does support or convey the collection type of the key's values.  (e.g. it currently implements `Set`, but there is no way to extend it to use an `Array`, `Vector` or `List` instead)
4) The code still uses `MultiMap` in various locations (like in the hashcode!), and the `CC[_]` is `MapFactory` (e.g. not `DictFactory`)
5) There are no other Dictionary terms in any of the Scala collections.  It's `Map` for any scala code, only the java converters have the mention of a dictionary.  `MultiDict` isn't scala idiomatic.

**Comment by SethTisue** [comment]
duplicate of #17? cc @joshlemer

**Comment by er1c** [comment]
@SethTisue thanks, I missed that other issue, closing and moving comment to the other issue.
